replicaCount: 1

image:
  repository: 818396592856.dkr.ecr.us-east-1.amazonaws.com/demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: weather-microservice
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: weather.example.com
      paths:
        - /

resources: {}
