apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  labels:
    environment: dev
spec:
  project: devops
  source:
    path: charts/devops/cluster-autoscaler
    repoURL: 'https://github.com/gpscarvell/demo.git'
    targetRevision: HEAD
    helm:
      valueFiles: [values-dev.yaml]
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
