apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd # Change this to the namespace where you want to deploy the application
spec:
  destination:
    server: 'https://kubernetes.default.svc' # Change this if your Kubernetes API server is different
    namespace: default # Change this to the target namespace for your ExternalDNS application
  source:
    repoURL: 'https://charts.bitnami.com/bitnami' # Replace this with the Helm chart repository URL for ExternalDNS
    targetRevision: 3.5.0 # Replace this with the specific chart version you want to use
    chart: external-dns # Replace this with the name of the ExternalDNS Helm chart
    helm:
      valueFiles:
        - external-dns-values.yaml # Optional: If you have custom values, provide the path to your values file
  project: default # Replace this with the ArgoCD project you want to deploy the application in
  syncPolicy:
    automated: # Set this to true if you want automatic sync, otherwise set it to false
      prune: true # Set this to true if you want ArgoCD to delete resources not defined in the Helm chart
      selfHeal: true # Set this to true if you want ArgoCD to self-heal resources to match the desired state
    syncOptions:
      - CreateNamespace=true # Set this to true if your Helm chart requires the creation of a new namespace
