apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-amq
  labels:
    io.kompose.service: amq
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    kompose.cmd: /home/beal/Downloads/migration-tools parse --docker-file /home/beal/Documents/terraform/kube-migration/Dev/activemq/docker-compose.yml
      --rancher-file /home/beal/Documents/terraform/kube-migration/Dev/activemq/rancher-compose.yml
    kompose.version: 1.20.0 (HEAD)
spec:
  type: {{ .Values.amq.type }}
  selector:
    io.kompose.service: amq
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.amq.ports | toYaml | nindent 2 -}}