
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: "demo.gscarvell.com"
    http:
      paths:
      - pathType: Prefix
        path: "/weather/washington-dc"
        backend:
          service:
            name: demo
            port:
              number: 8080
{{- end }}
