{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "weather-microservice.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "weather-microservice.name" . }}
    helm.sh/chart: {{ include "weather-microservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range .Values.ingress.hosts.paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "weather-microservice.fullname" . }}
                port:
                  number: http
          {{- end }}
{{- end }}
