
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: "demo.gscarvell.com"
    http:
      paths:
      - pathType: Prefix
        path: "/weather/washignton-dc"
        backend:
          service:
            name: {{ include "weather-microservice.fullname" . }}
            port:
              number: 80
{{- end }}
