
stages:
  - report


report:
  stage: report
  image: alpine:latest

  script:
    - apk add --no-cache curl unzip
    - curl -LO https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip
    - unzip terraform_1.5.3_linux_amd64.zip
    - mv terraform /usr/local/bin/
    - rm terraform_1.5.3_linux_amd64.zip
   
    - curl -LO https://github.com/cloudskiff/driftctl/releases/latest/download/driftctl_linux_amd64
    - mv driftctl_linux_amd64 /usr/local/bin/driftctl
    - chmod +x /usr/local/bin/driftctl

    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_REGION=$AWS_REGION


    - driftctl scan --from tfstate+s3://<bucket-name>-us-west-1/*/*/*/*/*.tfstate --from tfstate+s3://<bucket name>-us-west-1/*/*/*/*.tfstate

 