{{- if (and (not (and .Values.deploy.route.enabled (.Capabilities.APIVersions.Has "route.openshift.io/v1/Route"))) .Values.deploy.ingress.enabled) }}
{{- include "wildfly-common.ingress" (list . "wildfly.metadata.labels") -}}
{{- end -}}
