controller:
  nodeSelector:
    Environment: system

  k8sTagClusterId: demo

  serviceAccount:
    create: true # A service account will be created for you if set to true. Set to false if you want to use your own.
    name: ebs-csi-controller-sa # Name of the service-account to be used/created.
    annotations:

  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
      tolerationSeconds: 300
    - operator: "Exists"
      effect: "NoSchedule"

node:
  tolerateAllTaints: true