apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-topics
  labels:
    environment: demo
spec:
  project: default
  source:
    path: weather-microservice-helm/kafka-topics
    repoURL: 'https://github.com/gpscarvell/demo.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}