apiVersion: v2
name: external-dns
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: external-dns
  repository: https://charts.bitnami.com/bitnami
  version: 6.14.3