apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-atom
  labels:
    io.kompose.service: atom
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.atom.type }}
  selector:
    io.kompose.service: atom
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.atom.ports | toYaml | nindent 2 -}}