{{- if and (.Capabilities.APIVersions.Has "build.openshift.io/v1") (and .Values.build.enabled (eq .Values.build.mode "s2i")) }}
{{- include "wildfly-common.buildconfig-s2i-build-artifacts" (list . "wildfly.buildconfig-s2i-build-artifacts") -}}
{{- end -}}

{{- define "wildfly.buildconfig-s2i-build-artifacts" -}}
{{- include "wildfly.metadata.labels" . }}
spec:
  strategy:
    sourceStrategy:
      from:
        kind: {{ .Values.build.s2i.builderKind | default .Values.build.s2i.kind }}
        name: {{ include "wildfly.builderImage" . }}
{{- end -}}