{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
{{- if (and .Values.deploy.enabled .Values.deploy.route.enabled) }}
{{- include "wildfly-common.route" (list . "wildfly.metadata.labels") -}}
{{- end -}}
{{- end -}}