apiVersion: v2
name: external-secrets
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: external-secrets
  repository: https://charts.external-secrets.io
  version: v0.9.2