build:
  mode: s2i
  uri: https://github.com/wildfly/quickstart.git
  ref: 27.0.0.Final
  contextDir: microprofile-config
  s2i:
    featurePacks:
      - org.wildfly:wildfly-galleon-pack:27.0.0.Final
    galleonLayers:
      - jaxrs-server
      - microprofile-platform
deploy:
  replicas: 1
  env:
    - name: CONFIG_PROP
      value: Hello from OpenShift
  annotations:
    a8r.io/owner: wildfly.org
    a8r.io/description: >-
      This application demonstrates how to use MicroProfile Config to inject
      configuration from OpenShift in the application.
