build:
  uri: https://github.com/wildfly/quickstart.git
  ref: 27.0.0.Final
  contextDir: microprofile-config
  mode: bootable-jar
  env:
  - name: MAVEN_ARGS_APPEND
    # Use the bootable-jar-openshift profile to ensure that the application
    # can be deployed on OpenShift but disable JKube as the image will be 
    # built and deployed by this chart.
    value: -Pbootable-jar-openshift -Djkube.skip=true
deploy:
  replicas: 1
  env:
  - name: CONFIG_PROP
    value: Hello from OpenShift