apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  labels:
    environment: demo
spec:
  project: default
  source:
    path: weather-microservice-helm/kafka-operator
    repoURL: 'https://github.com/gpscarvell/demo.git'
    targetRevision: HEAD
    helm:
      valueFiles: [values.yaml]
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
