## nginx configuration
## Ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/index.md
##

controller:
  # This section refers to the creation of the IngressClass resource
  ## IngressClass resources are supported since k8s >= 1.18 and required since k8s >= 1.19
  ingressClassResource:
    # -- Name of the ingressClass
    name: nginx-public
    controllerValue: "k8s.io/nginx-ingress-public"
    # -- Is this ingressClass enabled or not
    enabled: true
    default: true

  ingressClass: nginx-public
  resources:
  #  limits:
  #    cpu: 100m
  #    memory: 90Mi
    requests:
      cpu: 100m
      memory: 90Mi
  containerPort:
    http: 80
    https: 443
  # config:
  #   ssl-redirect: "false" # we use `special` port to control ssl redirection
  #   server-snippet: |
  #     listen 8000;
  #     if ( $server_port = 80 ) {
  #        return 308 https://$host$request_uri;
  #     }
  # publishService required to Allow ELB Alias for DNS registration w/ external-dns
  kind: DaemonSet
  publishService:
    enabled: true
  service:
    # AWS Annotations for LoadBalaner
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: account=${account},jurisdiction=${jurisdiction},environment=global
      # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    # TLS (https) terminated at ELB, so internal endpoint is 'http'
    targetPorts:
      http: http
      https: https