build:
  uri: https://github.com/wildfly/quickstart.git
  ref: 27.0.0.Final
  contextDir: helloworld-rs
  s2i:
    featurePacks:
      - org.wildfly:wildfly-galleon-pack:27.0.0.Final
      - org.wildfly.cloud:wildfly-cloud-galleon-pack:2.0.0.Final
    galleonLayers:
      - jaxrs-server
deploy:
  tls:
    enabled: true
  route:
    tls:
      enabled: true
      termination: passthrough
  env:
    - name: HTTPS_KEYSTORE
      value: keystore.jks
    - name: HTTPS_PASSWORD
      valueFrom:
        secretKeyRef:
          key: keystore-password
          name: wildfly-app-secret
    - name: HTTPS_KEYSTORE_DIR
      value: /etc/wildfly-app-secret
  volumes:
    - name: wildfly-app-secret-volume
      secret:
        secretName: wildfly-app-secret
  volumeMounts:
    - name: wildfly-app-secret-volume
      mountPath: /etc/wildfly-app-secret
