replicaCount: 1

image:
  repository: your-docker-registry/weather-microservice-python
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: weather-microservice
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: weather.example.com
      paths:
        - /

resources: {}
