apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  labels:
    environment: dev
spec:
  project: default
  source:
    path: charts-k8s/applications/wildfly-charts/charts/wildfly
    repoURL: 'https://github.com/gpscarvell/demo.git'
    targetRevision: HEAD
    helm:
      valueFiles: [values.yaml]
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
