name: CI

on:
  push:
    branches: [ master ]

jobs:


  build:
    name: Build and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: demo

      run: |
        # Build a docker container and push it to ECR
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash .
        echo "Pushing image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}-$git_hash"
        
    - name: Update Version
      run: |
          #git_hash=$(git rev-parse --short "$GITHUB_SHA")
          #version=$(cat ./charts/applications/demo/values-dev.yaml | grep version: | awk '{print $2}')
          #sed -i "s|$version|${GITHUB_REF##*/}-$git_hash|" ./charts/applications/demo/values-dev.yaml

          # Get short git hash
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          # Extract the version from values-dev.yaml
          version=$(grep "version:" ./charts/applications/demo/values-dev.yaml | awk '{print $2}')

          # Ensure variables are printed for debugging purposes
          echo "Version: $version"
          echo "GITHUB_REF: ${GITHUB_REF##*/}"
          echo "Git hash: $git_hash"

          # Replace version using a different delimiter in sed to avoid conflicts
          sed -i "s|$version|${GITHUB_REF##*/}-$git_hash|" ./charts/applications/demo/values-dev.yaml



    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated
